USE ROLE ACCOUNTADMIN;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS STAGE_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

-- Database
CREATE DATABASE IF NOT EXISTS STAGE_DB;

-- Role
CREATE ROLE IF NOT EXISTS STAGE_ROLE;

-- Schema
CREATE SCHEMA IF NOT EXISTS STAGE_DB.STAGE_SCHEMA;

-- Grants
GRANT ROLE STAGE_ROLE TO USER DBT_USER;

GRANT USAGE ON WAREHOUSE STAGE_WH TO ROLE STAGE_ROLE;

GRANT USAGE ON DATABASE STAGE_DB TO ROLE STAGE_ROLE;

GRANT USAGE ON SCHEMA STAGE_DB.STAGE_SCHEMA TO ROLE STAGE_ROLE;

GRANT CREATE TABLE ON SCHEMA STAGE_DB.STAGE_SCHEMA TO ROLE STAGE_ROLE;

GRANT CREATE VIEW ON SCHEMA STAGE_DB.STAGE_SCHEMA TO ROLE STAGE_ROLE;

GRANT CREATE STAGE ON SCHEMA STAGE_DB.STAGE_SCHEMA TO ROLE STAGE_ROLE;

CREATE TABLE IF NOT EXISTS STAGE_DB.STAGE_SCHEMA.INGESTION_LOG (
    file_name STRING,
    file_hash STRING,
    file_size NUMBER,
    status STRING,
    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- accès base + schema
GRANT USAGE ON DATABASE STAGE_DB TO ROLE STAGE_ROLE;
GRANT USAGE ON SCHEMA STAGE_DB.STAGE_SCHEMA TO ROLE STAGE_ROLE;

-- droits sur la table de tracking
GRANT SELECT, INSERT, UPDATE ON TABLE STAGE_DB.STAGE_SCHEMA.INGESTION_LOG TO ROLE STAGE_ROLE;