-- Creation de dbt_role et dbt_user
-- Role
CREATE ROLE IF NOT EXISTS DBT_ROLE;
-- User
CREATE USER IF NOT EXISTS DBT_USER
    PASSWORD = 'MotDePasseSecure123!'
    DEFAULT_ROLE = DBT_ROLE
    DEFAULT_WAREHOUSE = 'DBT_WH'
    MUST_CHANGE_PASSWORD = FALSE;

-- Assigner le role
GRANT ROLE DBT_ROLE TO USER DBT_USER;
-- Warehouse
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;
-- Database
GRANT USAGE ON DATABASE DBT_DB TO ROLE DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE DBT_DB TO ROLE DBT_ROLE;
-- Schemas
GRANT ALL ON ALL SCHEMAS IN DATABASE DBT_DB TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE DBT_DB TO ROLE DBT_ROLE;
-- Tables
GRANT ALL ON ALL TABLES IN DATABASE DBT_DB TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE DBT_DB TO ROLE DBT_ROLE;
-- Views
GRANT ALL ON ALL VIEWS IN DATABASE DBT_DB TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN DATABASE DBT_DB TO ROLE DBT_ROLE;



-- Creation de metabas_role et metabase_user
-- Role
CREATE ROLE IF NOT EXISTS METABASE_ROLE;
-- User
CREATE USER IF NOT EXISTS METABASE_USER
    PASSWORD = 'MotDePasseSecure456!'
    DEFAULT_ROLE = METABASE_ROLE
    DEFAULT_WAREHOUSE = 'DBT_WH'
    MUST_CHANGE_PASSWORD = FALSE;

-- Assigner le role
GRANT ROLE METABASE_ROLE TO USER METABASE_USER;
-- Warehouse
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE METABASE_ROLE;
-- Database
GRANT USAGE ON DATABASE DBT_DB TO ROLE METABASE_ROLE;
-- Schema marts uniquement (lecture seule)
GRANT USAGE ON SCHEMA DBT_DB.PUBLIC_MARTS TO ROLE METABASE_ROLE;
-- Tables existantes
GRANT SELECT ON ALL TABLES IN SCHEMA DBT_DB.PUBLIC_MARTS TO ROLE METABASE_ROLE;
-- Futures tables
GRANT SELECT ON FUTURE TABLES IN SCHEMA DBT_DB.PUBLIC_MARTS TO ROLE METABASE_ROLE;
